# Generated by Django 5.0.2 on 2024-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Householdtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(null=True)),
                ('taskname', models.CharField(max_length=45, null=True)),
                ('createdby', models.CharField(max_length=45, null=True)),
                ('timescompleted', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('iscustom', models.BooleanField(null=True)),
                ('taskcreated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45, null=True)),
                ('lastname', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('userid', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('tasks_completed', models.IntegerField(null=True)),
                ('tasks_created', models.IntegerField(null=True)),
                ('isadmin', models.BooleanField(null=True)),
                ('householdid', models.IntegerField(null=True)),
            ],
        ),
    ]
