# Generated by Django 5.0.2 on 2024-02-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_created', models.IntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('householdid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Householdtasks',
            fields=[
                ('householdtaskid', models.AutoField(primary_key=True, serialize=False)),
                ('times_completed', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highandtidycomponent1.tasks')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highandtidycomponent1.users')),
            ],
        ),
    ]
