# Generated by Django 5.0.4 on 2024-04-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highandtidycomponent1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='householdid',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=45)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highandtidycomponent1.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highandtidycomponent1.users')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highandtidycomponent1.households')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='household_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='highandtidycomponent1.households'),
        ),
        migrations.DeleteModel(
            name='Householdtasks',
        ),
    ]
