# Generated by Django 5.0.4 on 2024-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highandtidycomponent1', '0002_households_remove_users_householdid_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='household_name',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
