# Generated by Django 5.0.7 on 2024-09-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highandtidycomponent1', '0003_households_household_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
