# Generated by Django 5.1.1 on 2024-10-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highandtidycomponent1', '0004_tasks_task_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='lname',
        ),
    ]
