# Generated by Django 5.1.1 on 2024-10-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highandtidycomponent1', '0005_rename_firstname_users_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
